### ISSUE TITLE
Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by sanchitsamuel** [Paytm-Payments/Paytm_Android_App_Kit#16]
`05-09 19:10:48.192 21430-21430/com.lernr.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.lernr.app, PID: 21430
                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lernr.app/com.paytm.pgsdk.PaytmPGActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2681)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2742)
                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1489)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6178)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
                                                                Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
                                                                   at com.paytm.pgsdk.PaytmPGActivity.startTransaction(PaytmPGActivity.java:364)
                                                                   at com.paytm.pgsdk.PaytmPGActivity.onCreate(PaytmPGActivity.java:101)
                                                                   at android.app.Activity.performCreate(Activity.java:6682)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2634)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2742) 
                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1489) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:154) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6178) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) `

App crashes with this issue.

**Comment by Veeresh8** [comment]
Facing the same issue here

**Comment by sridharnalam** [comment]
@chetanurmaliya
I am facing this issue till PGSDK_V2.1.jar.
Does this Command : compile 'com.paytm.pgsdk:pgsdk:1.0.6' update solve this issue ?

**Comment by chetanurmaliya** [comment]
As mentioned in [readme](https://github.com/Paytm-Payments/Paytm_Android_App_Kit/tree/master/PaytmSDK).

No need to use PGSDK_V2.1.jar file.
Just use the Gradle Dependency: Command:  compile 'com.paytm.pgsdk:pgsdk:1.0.6'

Note: 
1. If you have the Jar file, please Remove the jar file and jar dependency from the project. 
2. Kindly change the import statements accordingly.

**Comment by axaygadekar** [comment]
Make sure you are not passing any null param.

**Comment by RishitoshGour** [comment]
> As mentioned in [readme](https://github.com/Paytm-Payments/Paytm_Android_App_Kit/tree/master/PaytmSDK).
> 
> No need to use PGSDK_V2.1.jar file.
> Just use the Gradle Dependency: Command: compile 'com.paytm.pgsdk:pgsdk:1.0.6'
> 
> Note:
> 
> 1. If you have the Jar file, please Remove the jar file and jar dependency from the project.
> 2. Kindly change the import statements accordingly.


Can you please tell me step by step how  can we create AAR file from android studio using paytm Gradle Dependency. I just want to make AAR file by adding paytm gradle dependency using android studio and expose one methon that is initializePaytmPayment(). Please mention each step as i am new to android studio and in learning phase. Thanks in advance.
