### ISSUE TITLE
Application crashes when pressed back from Paytm screen 

### ISSUE THREAD

**Issue by ram-readwhere** [Paytm-Payments/Paytm_Android_App_Kit#22]
`java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map com.paytm.pgsdk.PaytmOrder.getRequestParamMap()' on a null object reference 

at com.paytm.pgsdk.PaytmWebView$PaytmWebViewClient.onPageFinished(PaytmWebView.java:115)`

**Comment by chetanurmaliya** [comment]
Did you get any solution.
I am also facing the same problem. 


`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map com.paytm.pgsdk.c.a()' on a null object reference
       at com.paytm.pgsdk.PaytmWebView$PaytmWebViewClient.onPageFinished(PaytmWebView.java:135)
       at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:196)
       at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6165)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)`

**Comment by ram-readwhere** [comment]
Hi chetanurmaliya, 

This issue is with sandbox(testing) account of Paytm only. It did not re produce when live credentials were updated.

**Comment by pravinappsplanet** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map com.paytm.pgsdk.PaytmOrder.getRequestParamMap()

**Comment by chetanurmaliya** [comment]
New version has this issue. Please use [PGSDK_V2.0.jar](https://github.com/Paytm-Payments/Paytm_Android_App_Kit/tree/1065bbdbfbf323c105b251a0fc67d2d966ad247d/PaytmSDK)

**Comment by shubhanshusingh** [comment]
I am facing same issue with PGSDK_V2.1.jar,help?

**Comment by chetanurmaliya** [comment]
Hi shubhanshusingh, 

Please use [PGSDK_V2.0.jar](https://github.com/Paytm-Payments/Paytm_Android_App_Kit/tree/1065bbdbfbf323c105b251a0fc67d2d966ad247d/PaytmSDK)
 until new version will update. 

PGSDK_V2.1.jar version has this issue.

**Comment by shubhanshusingh** [comment]
alright thanks

**Comment by sankar-novel** [comment]
How to resolve this issue in **PGSDK_V2.1.jar**

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map com.paytm.pgsdk.PaytmOrder.getRequestParamMap()' on a null object reference
       at com.paytm.pgsdk.PaytmWebView$PaytmWebViewClient.onPageFinished(Unknown Source)
       at com.android.webview.chromium.Ap.onPageFinished(WebViewContentsClientAdapter.java:217)
       at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:70)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by chetanurmaliya** [comment]
Hi sankar-novel, 

PGSDK_V2.1.jar version has this issue.

Use Gradle dependency  
Command : compile 'com.paytm.pgsdk:pgsdk:1.0.6'

Please check latest [readme](https://github.com/Paytm-Payments/Paytm_Android_App_Kit/tree/master/PaytmSDK)

**Comment by sidpal7747** [comment]
Hello, I am using Gradle dependency 'com.paytm.pgsdk:pgsdk:1.0.6' and I am getting the fatal error.

Caused by java.lang.NullPointerException: Attempt to invoke virtual method '[REDACTED_DOMAIN_NAME] com.paytm.pgsdk.PaytmOrder.getRequestParamMap()' on a null object reference
