### ISSUE TITLE
java.lang.NoClassDefFoundError: net.one97.paytm.nativesdk.transcation.PayActivity

### ISSUE THREAD

**Issue by Sunaina015** [Paytm-Payments/Paytm_Android_App_Kit#59]
Hi,
Please help me i  am finding this issue-
02-23 16:16:20.511 6183-6487/w3bminds.engVarta.app D/FA: Logging event (FE): app_exception(_ae), Bundle[{firebase_event_origin(_o)=clx, _r=1, firebase_screen_class(_sc)=PaytmMainActivity, firebase_screen_id(_si)=-6008727572610862121, timestamp=1550918780209, fatal=1}]
    
    --------- beginning of crash
02-23 16:16:20.529 6183-6183/w3bminds.engVarta.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: w3bminds.engVarta.app, PID: 6183
    java.lang.NoClassDefFoundError: net.one97.paytm.nativesdk.transcation.PayActivity
        at net.one97.paytm.nativesdk.instruments.netbanking.viewmodel.NetBankingViewModel.goForTransaction(NetBankingViewModel.java:232)
        at net.one97.paytm.nativesdk.instruments.netbanking.viewmodel.NetBankingViewModel.completeTransaction(NetBankingViewModel.java:253)
        at net.one97.paytm.nativesdk.login.view.fragment.LoginFragment$CashierInstrumentCom.closeCashier(LoginFragment.java:197)
        at net.one97.paytm.nativesdk.instruments.Instruments.closeCashierSheet(Instruments.java:41)
        at net.one97.paytm.nativesdk.instruments.netbanking.view.NetBankingView.closeCachierSheet(NetBankingView.java:244)
        at net.one97.paytm.nativesdk.instruments.netbanking.viewmodel.NetBankingViewModel.setSelectedInstrument(NetBankingViewModel.java:276)
        at net.one97.paytm.nativesdk.instruments.netbanking.view.NetBankingView$2.onItemClick(NetBankingView.java:173)
        at net.one97.paytm.nativesdk.instruments.netbanking.listeners.RecyclerItemClickListner.onInterceptTouchEvent(RecyclerItemClickListner.java:40)
        at android.support.v7.widget.RecyclerView.dispatchOnItemTouchIntercept(RecyclerView.java:2821)
        at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:2867)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2109)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2405)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2870)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2366)
        at android.view.View.dispatchPointerEvent(View.java:9539)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4289)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4152)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3691)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3744)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3710)
    	at android.view

**Comment by subbupampana** [comment]
Try this
implementation ('com.paytm.easypay:easypay:1.1.4'){
    exclude group:'com.android.support'
}
